# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc “Submit a new Beta Build to Firebase Dev”
    lane :firebase do |options|
        gradle(task: “assemble”, build_type: “debug”)
        firebase_app_distribution(
            app: “1:505172189088:android:9d4ff14f99cd85b9f54ec5”,
            groups: “testers”,
            release_notes: message = "nueva version"
        )
        google_chat(
            imageUrl: 'https://media.giphy.com/media/Nx0rz3jtxtEre/source.gif',
            webhook: 'https://chat.googleapis.com/v1/spaces/AAAAIkxhykk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=7a4AsdWmpb3KaZ3-bNkxduhIZ5NWISTXWg4mTz7td8w%3D',
            title: 'hello there',
            description: 'Nueva versión de C3P0!!',
            section1Title: 'Tarjeta a Testear',
            section1Description: options[:text],
            buttonTitle: "Tarjeta Jira",
            buttonUrl: "https://kevayok540.atlassian.net/" + options[:text],
            )
  end
end
